//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BATCH_MANAGEMENT_DBEntities : DbContext
    {
        public BATCH_MANAGEMENT_DBEntities()
            : base("name=BATCH_MANAGEMENT_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BATCH> BATCHes { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
    
        public virtual int BATCH_ADD_SP(Nullable<int> cOURSE_ID, Nullable<int> bATCH_ID, string bATCH_NAME, string bATCH_DURATION)
        {
            var cOURSE_IDParameter = cOURSE_ID.HasValue ?
                new ObjectParameter("COURSE_ID", cOURSE_ID) :
                new ObjectParameter("COURSE_ID", typeof(int));
    
            var bATCH_IDParameter = bATCH_ID.HasValue ?
                new ObjectParameter("BATCH_ID", bATCH_ID) :
                new ObjectParameter("BATCH_ID", typeof(int));
    
            var bATCH_NAMEParameter = bATCH_NAME != null ?
                new ObjectParameter("BATCH_NAME", bATCH_NAME) :
                new ObjectParameter("BATCH_NAME", typeof(string));
    
            var bATCH_DURATIONParameter = bATCH_DURATION != null ?
                new ObjectParameter("BATCH_DURATION", bATCH_DURATION) :
                new ObjectParameter("BATCH_DURATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BATCH_ADD_SP", cOURSE_IDParameter, bATCH_IDParameter, bATCH_NAMEParameter, bATCH_DURATIONParameter);
        }
    
        public virtual int BATCH_DELETE_SP(Nullable<int> bATCH_ID)
        {
            var bATCH_IDParameter = bATCH_ID.HasValue ?
                new ObjectParameter("BATCH_ID", bATCH_ID) :
                new ObjectParameter("BATCH_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BATCH_DELETE_SP", bATCH_IDParameter);
        }
    
        public virtual ObjectResult<BATCH_SELECT_SP_Result> BATCH_SELECT_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BATCH_SELECT_SP_Result>("BATCH_SELECT_SP");
        }
    
        public virtual int BATCH_UPDATE_SP(Nullable<int> bATCH_ID, string bATCH_NAME, string bATCH_DURATION)
        {
            var bATCH_IDParameter = bATCH_ID.HasValue ?
                new ObjectParameter("BATCH_ID", bATCH_ID) :
                new ObjectParameter("BATCH_ID", typeof(int));
    
            var bATCH_NAMEParameter = bATCH_NAME != null ?
                new ObjectParameter("BATCH_NAME", bATCH_NAME) :
                new ObjectParameter("BATCH_NAME", typeof(string));
    
            var bATCH_DURATIONParameter = bATCH_DURATION != null ?
                new ObjectParameter("BATCH_DURATION", bATCH_DURATION) :
                new ObjectParameter("BATCH_DURATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BATCH_UPDATE_SP", bATCH_IDParameter, bATCH_NAMEParameter, bATCH_DURATIONParameter);
        }
    
        public virtual int COURSE_ADD_SP(Nullable<int> cOURSE_ID, string cOURSE_NAME, string tEACHER_NAME)
        {
            var cOURSE_IDParameter = cOURSE_ID.HasValue ?
                new ObjectParameter("COURSE_ID", cOURSE_ID) :
                new ObjectParameter("COURSE_ID", typeof(int));
    
            var cOURSE_NAMEParameter = cOURSE_NAME != null ?
                new ObjectParameter("COURSE_NAME", cOURSE_NAME) :
                new ObjectParameter("COURSE_NAME", typeof(string));
    
            var tEACHER_NAMEParameter = tEACHER_NAME != null ?
                new ObjectParameter("TEACHER_NAME", tEACHER_NAME) :
                new ObjectParameter("TEACHER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COURSE_ADD_SP", cOURSE_IDParameter, cOURSE_NAMEParameter, tEACHER_NAMEParameter);
        }
    
        public virtual int COURSE_DELETE_SP(Nullable<int> cOURSE_ID)
        {
            var cOURSE_IDParameter = cOURSE_ID.HasValue ?
                new ObjectParameter("COURSE_ID", cOURSE_ID) :
                new ObjectParameter("COURSE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COURSE_DELETE_SP", cOURSE_IDParameter);
        }
    
        public virtual ObjectResult<COURSE_SELECT_SP_Result> COURSE_SELECT_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<COURSE_SELECT_SP_Result>("COURSE_SELECT_SP");
        }
    
        public virtual int COURSE_UPDATE_SP(Nullable<int> cOURSE_ID, string cOURSE_NAME, string tEACHER_NAME)
        {
            var cOURSE_IDParameter = cOURSE_ID.HasValue ?
                new ObjectParameter("COURSE_ID", cOURSE_ID) :
                new ObjectParameter("COURSE_ID", typeof(int));
    
            var cOURSE_NAMEParameter = cOURSE_NAME != null ?
                new ObjectParameter("COURSE_NAME", cOURSE_NAME) :
                new ObjectParameter("COURSE_NAME", typeof(string));
    
            var tEACHER_NAMEParameter = tEACHER_NAME != null ?
                new ObjectParameter("TEACHER_NAME", tEACHER_NAME) :
                new ObjectParameter("TEACHER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COURSE_UPDATE_SP", cOURSE_IDParameter, cOURSE_NAMEParameter, tEACHER_NAMEParameter);
        }
    
        public virtual int STUDENT_ADD_SP(Nullable<int> bATCH_ID, Nullable<int> sTUDENT_ID, string sTUDENT_NAME, Nullable<int> sTUDENT_AGE, string sTUDENT_EMAILID)
        {
            var bATCH_IDParameter = bATCH_ID.HasValue ?
                new ObjectParameter("BATCH_ID", bATCH_ID) :
                new ObjectParameter("BATCH_ID", typeof(int));
    
            var sTUDENT_IDParameter = sTUDENT_ID.HasValue ?
                new ObjectParameter("STUDENT_ID", sTUDENT_ID) :
                new ObjectParameter("STUDENT_ID", typeof(int));
    
            var sTUDENT_NAMEParameter = sTUDENT_NAME != null ?
                new ObjectParameter("STUDENT_NAME", sTUDENT_NAME) :
                new ObjectParameter("STUDENT_NAME", typeof(string));
    
            var sTUDENT_AGEParameter = sTUDENT_AGE.HasValue ?
                new ObjectParameter("STUDENT_AGE", sTUDENT_AGE) :
                new ObjectParameter("STUDENT_AGE", typeof(int));
    
            var sTUDENT_EMAILIDParameter = sTUDENT_EMAILID != null ?
                new ObjectParameter("STUDENT_EMAILID", sTUDENT_EMAILID) :
                new ObjectParameter("STUDENT_EMAILID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STUDENT_ADD_SP", bATCH_IDParameter, sTUDENT_IDParameter, sTUDENT_NAMEParameter, sTUDENT_AGEParameter, sTUDENT_EMAILIDParameter);
        }
    
        public virtual int STUDENT_DELETE_SP(Nullable<int> sTUDENT_ID)
        {
            var sTUDENT_IDParameter = sTUDENT_ID.HasValue ?
                new ObjectParameter("STUDENT_ID", sTUDENT_ID) :
                new ObjectParameter("STUDENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STUDENT_DELETE_SP", sTUDENT_IDParameter);
        }
    
        public virtual ObjectResult<STUDENT_SELECT_SP_Result> STUDENT_SELECT_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STUDENT_SELECT_SP_Result>("STUDENT_SELECT_SP");
        }
    
        public virtual int STUDENT_UPDATE_SP(Nullable<int> sTUDENT_ID, string sTUDENT_NAME, Nullable<int> sTUDENT_AGE, string sTUDENT_EMAILID)
        {
            var sTUDENT_IDParameter = sTUDENT_ID.HasValue ?
                new ObjectParameter("STUDENT_ID", sTUDENT_ID) :
                new ObjectParameter("STUDENT_ID", typeof(int));
    
            var sTUDENT_NAMEParameter = sTUDENT_NAME != null ?
                new ObjectParameter("STUDENT_NAME", sTUDENT_NAME) :
                new ObjectParameter("STUDENT_NAME", typeof(string));
    
            var sTUDENT_AGEParameter = sTUDENT_AGE.HasValue ?
                new ObjectParameter("STUDENT_AGE", sTUDENT_AGE) :
                new ObjectParameter("STUDENT_AGE", typeof(int));
    
            var sTUDENT_EMAILIDParameter = sTUDENT_EMAILID != null ?
                new ObjectParameter("STUDENT_EMAILID", sTUDENT_EMAILID) :
                new ObjectParameter("STUDENT_EMAILID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STUDENT_UPDATE_SP", sTUDENT_IDParameter, sTUDENT_NAMEParameter, sTUDENT_AGEParameter, sTUDENT_EMAILIDParameter);
        }
    
        public virtual int REGISTRATION_ADD_SP(string uSER_NAME, string uSER_PASSWORD, string uSER_EMAIL, Nullable<decimal> uSER_PHNNO)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            var uSER_EMAILParameter = uSER_EMAIL != null ?
                new ObjectParameter("USER_EMAIL", uSER_EMAIL) :
                new ObjectParameter("USER_EMAIL", typeof(string));
    
            var uSER_PHNNOParameter = uSER_PHNNO.HasValue ?
                new ObjectParameter("USER_PHNNO", uSER_PHNNO) :
                new ObjectParameter("USER_PHNNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REGISTRATION_ADD_SP", uSER_NAMEParameter, uSER_PASSWORDParameter, uSER_EMAILParameter, uSER_PHNNOParameter);
        }
    
        public virtual ObjectResult<REGISTRATION_SELECT_SP_Result> REGISTRATION_SELECT_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REGISTRATION_SELECT_SP_Result>("REGISTRATION_SELECT_SP");
        }
    
        public virtual ObjectResult<SEE_NAME_Result> SEE_NAME(string uSER_NAME, string uSER_PASSWORD)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEE_NAME_Result>("SEE_NAME", uSER_NAMEParameter, uSER_PASSWORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SEE_NO_OF_STUDENT(Nullable<int> bATCH_ID)
        {
            var bATCH_IDParameter = bATCH_ID.HasValue ?
                new ObjectParameter("BATCH_ID", bATCH_ID) :
                new ObjectParameter("BATCH_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SEE_NO_OF_STUDENT", bATCH_IDParameter);
        }
    
        public virtual int ADD_USER_MESSAGE(string nAME, string eMAIL, string mESSAGE)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var mESSAGEParameter = mESSAGE != null ?
                new ObjectParameter("MESSAGE", mESSAGE) :
                new ObjectParameter("MESSAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_USER_MESSAGE", nAMEParameter, eMAILParameter, mESSAGEParameter);
        }
    
        public virtual ObjectResult<SEE_SPECIFIC_BATCHES_Result> SEE_SPECIFIC_BATCHES(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEE_SPECIFIC_BATCHES_Result>("SEE_SPECIFIC_BATCHES", iDParameter);
        }
    
        public virtual ObjectResult<SEE_SPECIFIC_STUDENTS_Result> SEE_SPECIFIC_STUDENTS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEE_SPECIFIC_STUDENTS_Result>("SEE_SPECIFIC_STUDENTS", iDParameter);
        }
    }
}
