//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public Nullable<int> BATCH_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public Nullable<int> STUDENT_AGE { get; set; }
        public string STUDENT_EMAILID { get; set; }
    
        public virtual BATCH BATCH { get; set; }
    }
}
